### ISSUE TITLE
The link lambda needs to be in context of the instance 

### ISSUE THREAD

**Issue by philsturgeon** [wework/rails-sunset#3]
I'd love to be able to use URL helpers instead of forcing text links for example. Not entirely sure how to do that.

**Comment by vasilakisfil** [comment]
@philsturgeon you can do that by changing the lambda's binding using `instance_exec`, just before you call it.

**Comment by vasilakisfil** [comment]
You can see an example here: https://blog.kollegorna.se/things-i-learned-developing-ruby-and-rails-apps-over-the-past-3-years-e04ce780f5b1#e4dc
